routes/web.php
<?php

use App\Http\Controllers\Auth\AttemptLoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\ViewLoginController;
use App\Http\Controllers\Web\CompanyController;
use App\Http\Controllers\Web\DeliveryProductController;
use App\Http\Controllers\Web\FormulaController;
use App\Http\Controllers\Web\HistoryController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Web\ProductionPlanController;
use App\Http\Controllers\Web\ReceiveItemController;
use App\Http\Controllers\Web\ReleaseMaterialController;
use App\Http\Controllers\Web\RoleController;
use App\Http\Controllers\Web\UserController;
use App\Http\Controllers\Web\WarehouseController;
use App\Http\Controllers\Web\WarehouseRackController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', ViewLoginController::class)->name('login');
Route::post('login', AttemptLoginController::class)->name('attemptLogin');
Route::get('logout', LogoutController::class)->middleware('auth')->name('logout');

Route::middleware('auth')->group(function () {
    Route::view('/', 'pages.home')->name('home');
});

Route::middleware('auth')->group(function () {
    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);

    Route::get('warehouses/export', [WarehouseController::class, 'export'])->name('warehouses.export');
    Route::post('warehouses/import', [WarehouseController::class, 'import'])->name('warehouses.import');
    Route::resource('warehouses', WarehouseController::class);

    Route::resource('warehouses.racks', WarehouseRackController::class);

    Route::get('companies/export', [CompanyController::class, 'export'])->name('companies.export');
    Route::post('companies/import', [CompanyController::class, 'import'])->name('companies.import');
    Route::resource('companies', CompanyController::class);

    Route::get('products/{product}/history', [HistoryController::class, 'showProductHistory']);
    Route::get('products/export', [ProductController::class, 'export'])->name('products.export');
    Route::post('products/import', [ProductController::class, 'import'])->name('products.import');
    Route::resource('products', ProductController::class);

    Route::resource('receives', ReceiveItemController::class);
    Route::resource('deliveries', DeliveryProductController::class);

    Route::get('formulas/{formula}/input', [FormulaController::class, 'loadFragmentInputFormula']);
    Route::resource('formulas', FormulaController::class);

    Route::get('plans/{plan}/input', [ProductionPlanController::class, 'loadFragmentInputMaterial']);
    Route::resource('plans', ProductionPlanController::class);

    Route::resource('releases', ReleaseMaterialController::class);
});

app/View/Components/Layouts/BaseCardComponent.php
<?php

namespace App\View\Components\Layouts;

use Illuminate\View\Component;

class BaseCardComponent extends Component
{
    /**
     * The theme mode for the card (full or outline).
     *
     * @var string
     */
    public $themeMode;

    /**
     * The theme color for the card.
     *
     * @var string
     */
    public $theme;

    /**
     * The CSS class for the card body.
     *
     * @var string
     */
    public $bodyClass;

    /**
     * The custom component to be displayed inside the card body.
     *
     * @var mixed
     */
    public $dynamicComponent;

    /**
     * The title for the card header.
     *
     * @var string|null
     */
    public $cardTitle;

    /**
     * Whether or not the card is collapsible.
     *
     * @var string|null
     */
    public $cardCollapsible;

    public function __construct($cardTitle = null, $themeMode = 'outline', $theme = 'primary', $dynamicComponent = null, $bodyClass = null, $cardCollapsible = null)
    {
        $this->themeMode = $themeMode;
        $this->theme = $theme;
        $this->cardTitle = $cardTitle;
        $this->cardCollapsible = $cardCollapsible;
        $this->bodyClass = $bodyClass;
        $this->dynamicComponent = $dynamicComponent;
    }

    /**
     * Generate the CSS class for the card based on its properties.
     *
     * @return string The CSS class for the card.
     */
    public function cardClass()
    {
        $classes = ['card'];

        // Add theme-related classes.
        if (isset($this->theme)) {
            $base = $this->themeMode === 'full' ? 'bg' : 'card';
            $classes[] = "{$base}-{$this->theme}";

            if ($this->themeMode === 'outline') {
                $classes[] = 'card-outline';
            }
        }

        // Add collapsible-related classes.
        if ($this->cardCollapsible === 'collapsed') {
            $classes[] = 'collapsed-card';
        }

        // Return the concatenated string of classes.
        return implode(' ', $classes);
    }

    /**
     * Generate the CSS class for the card body based on its properties.
     *
     * @return string The CSS class for the card body.
     */
    public function cardBodyClass()
    {
        $classes = ['card-body'];

        if (isset($this->bodyClass)) {
            $classes[] = $this->bodyClass;
        }

        // Return the concatenated string of classes.
        return implode(' ', $classes);
    }

    /**
     * Check if the card has any tools (e.g. collapsible button).
     *
     * @return bool Whether or not the card has any tools.
     */
    public function hasCardTools()
    {
        return isset($this->cardCollapsible);
    }

    /**
     * Render the BaseCardComponent view.
     *
     * @return \Illuminate\Contracts\View\View The rendered view.
     */
    public function render()
    {
        return view('components.layouts.base-card-component');
    }
}

app/View/Components/Layouts/BaseFormComponent.php
<?php

namespace App\View\Components\Layouts;

use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Illuminate\View\Component;

/**
 * Class BaseFormComponent
 * @package App\View\Components\Layouts
 *
 * A reusable component for creating and updating forms
 */
class BaseFormComponent extends Component
{
    /**
     * The title of the form
     * @var string
     */
    public string $title;

    /**
     * The keys of the route
     * @var array
     */
    public array $routeKeys;

    /**
     * The prefix of the route
     * @var string
     */
    public string $routePrefix;

    /**
     * The model to be updated, if any
     * @var object|null
     */
    public ?object $model = null;

    /**
     * The parameters for the route
     * @var array
     */
    public array $param;

    /**
     * BaseFormComponent constructor.
     * @param string $title The title of the form
     * @param string $routePrefix The prefix of the route
     * @param mixed|null $param The parameters for the route, if any
     */
    public function __construct(string $title, string $routePrefix, $param = null)
    {
        $this->title = $title;
        $this->routePrefix = $routePrefix;
        $this->param = Arr::wrap($param);

        // Split the route prefix into an array of keys
        $this->routeKeys = collect(explode('.', $routePrefix))->map(fn ($key) => Str::singular($key))->toArray();

        // The last parameter is assumed to be the model (if any)
        $this->model = Arr::last($this->param);
    }

    /**
     * Returns the title of the form with "Create" or "Update" appended, depending on whether a model is present
     * @return string
     */
    public function getTitle(): string
    {
        return $this->model ? "{$this->title} Update" : "{$this->title} Create";
    }

    /**
     * Returns the URL for the form submission, with any parameters included
     * @return string
     */
    public function getRoute(): string
    {
        $param = [];

        // Map the route keys to the corresponding parameter IDs
        $param = collect($this->param)->mapWithKeys(function ($param, $index) {
            return [$this->routeKeys[$index] => $param['id']];
        })->toArray();

        // Return the URL with the appropriate action ("store" for create, "update" for update)
        return route("{$this->routePrefix}." . ($this->model ? 'update' : 'store'), $param);
    }

    /**
     * Returns the HTTP method for the form submission (either "POST" or "PUT")
     * @return string
     */
    public function getMethod(): string
    {
        return $this->model ? 'PUT' : 'POST';
    }

    /**
     * Render method that returns the view to be rendered
     * @return \Illuminate\Contracts\View\View
     */
    public function render()
    {
        return view('components.layouts.base-form-component');
    }
}

app/View/Components/Layouts/SidebarMenu.php
<?php

namespace App\View\Components\Layouts;

use Illuminate\View\Component;

class SidebarMenu extends Component
{
    /**
     * The URL to redirect to
     *
     * @var string
     */
    public string $url;

    /**
     * The icon to display for the menu item
     *
     * @var string
     */
    public string $icon;

    /**
     * The label to display for the menu item
     *
     * @var string
     */
    public string $label;

    /**
     * The permission required to view this menu item
     *
     * @var string|null
     */
    public ?string $permission;

    /**
     * The current URL, cached in the constructor
     *
     * @var string|null
     */
    private string $currentUrl;

    /**
     * Create a new component instance.
     *
     * @param string $label The label to display for the menu item
     * @param string $url The URL to redirect to
     * @param string $icon The icon to display for the menu item
     * @return void
     */
    public function __construct($label = 'Menu', string $url = '#', string $icon = 'fas fa-circle nav-icon', string $permission = null)
    {
        $this->label        = $label;
        $this->icon         = $icon;
        $this->url          = $url;
        $this->permission   = $permission;

        $this->currentUrl = url()->current();
    }

    /**
     * Get if this sidebar menu item is active
     */
    public function isActive(): bool
    {
        return $this->url === $this->currentUrl ? 'active' : '';
    }

    /**
     * Get if the current user has permission to view this menu item
     */
    public function hasPermission(): bool
    {
        return $this->permission ? auth()->user()->hasPermissionTo($this->permission) : true;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return $this->hasPermission() ? view('components.layouts.sidebar-menu') : '';
    }
}

resources/views/_layouts/base.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>@yield('title')</title>

    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!-- Load CSS yang di-extend oleh child view -->
    @yield('css')
    <!-- Load CSS yang di-push oleh child view -->
    @stack('css')

    <!-- Load main CSS -->
    @vite(['resources/css/app.scss'])

    <!-- Style untuk menghilangkan tombol spinner pada input number -->
    <style>
        /* Chrome, Safari, Edge, Opera */
        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        /* Firefox */
        input[type=number] {
            -moz-appearance: textfield;
        }
    </style>
</head>

<body class="hold-transition sidebar-mini sidebar-collapse">
    <div class="wrapper">

        <!-- Include navbar -->
        @include('_layouts.navbar')
        <!-- Include sidebar -->
        @include('_layouts.sidebar')

        <div class="content-wrapper">
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <!-- Title Page -->
                            <h1>@yield('header-content')</h1>
                        </div>
                        <div class="col-sm-6">
                            <!-- Breadcrumb -->
                            <ol class="breadcrumb float-sm-right">
                                @yield('breadcumb')
                            </ol>
                        </div>
                    </div>
            </section>

            <!-- Main content -->
            <section class="content">
                <!-- Main Content Page -->
                @yield('content')
            </section>
            <!-- /.content -->
        </div>

        <!-- Include footer -->
        @include('_layouts.footer')

        <!-- Control sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>

        <!-- Load main JS -->
        @vite(['resources/js/app.js'])

        <!-- Load JS yang di-extend oleh child view -->
        @yield('js')
        <!-- Load JS yang di-push oleh child view -->
        @stack('js')
    </div>
</body>

</html>

resources/views/_layouts/footer.blade.php
<footer class="main-footer">
<div class="float-right d-none d-sm-block">
  <b>Version</b> 1.0.0
</div>
<strong>Copyright &copy; 2022 <a href="#">PT. Focus Color Indonesia</a>.</strong> All rights reserved.
</footer>

resources/views/_layouts/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
</nav>

resources/views/_layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand logo -->
    <a href="#" class="brand-link">
        <img src="#" alt="" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">FOCSystem</span>
    </a>

    <div class="sidebar">
        <!-- User panel -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src='https://ui-avatars.com/api/?name={{ Auth::user()->username }}&background=0D8ABC&color=fff'
                    class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ Auth::user()->username }}</a>
            </div>
        </div>

        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Sidebar menu items -->
                <x-sidebar-menu label='Home' :url="route('home')" icon='fas fa-home' />

                <li class="nav-header"></li>
                <x-sidebar-menu label='Product' :url="route('products.index')" icon='fas fa-boxes' />

                <li class="nav-header">LABORATORY</li>
                <x-sidebar-menu label='Formula' :url="route('formulas.index')" icon='fas fa-flask' />

                <li class="nav-header">PPIC</li>
                <x-sidebar-menu label='Production Plan' :url="route('plans.index')" icon='fas fa-clipboard-list' />

                <li class="nav-header">DISTRIBUTION CENTER</li>
                <x-sidebar-menu label='Receive Item' :url="route('receives.index')" icon='fas fa-truck-loading' permission='receive_view'/>
                <x-sidebar-menu label='Delivery Product' :url="route('deliveries.index')" icon='fas fa-truck' permission='delivery_view'/>

                <li class="nav-header">WAREHOUSE</li>
                <x-sidebar-menu label='Release Material' :url="route('releases.index')" icon='fas fa-clipboard-check' />

                <li class="nav-header">MASTER DATA</li>
                <x-sidebar-menu label='Relation Company' :url="route('companies.index')" icon='fas fa-building' permission='master_company_view'/>
                <x-sidebar-menu label='Warehouse' :url="route('warehouses.index')" icon='fas fa-warehouse' permission='master_warehouse_view' />

                @can('admin_view')<li class="nav-header">ADMINISTRATION</li>@endcan
                <x-sidebar-menu label='Users Management' :url="route('users.index')" icon='fas fa-users' permission='admin_view' />
                <x-sidebar-menu label='Roles Management' :url="route('roles.index')" icon='fas fa-user-tag' permission='admin_view' />

                <li class="nav-header">PROFILE</li>
                <x-sidebar-menu label='Logout' :url="route('logout')" icon='fas fa-sign-out-alt' />
            </ul>
        </nav>
    </div>
</aside>