routes/web.php
<?php

use App\Http\Controllers\Auth\AttemptLoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\ViewLoginController;
use App\Http\Controllers\Web\CompanyController;
use App\Http\Controllers\Web\DeliveryProductController;
use App\Http\Controllers\Web\FormulaController;
use App\Http\Controllers\Web\HistoryController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Web\ProductionPlanController;
use App\Http\Controllers\Web\ReceiveItemController;
use App\Http\Controllers\Web\ReleaseMaterialController;
use App\Http\Controllers\Web\RoleController;
use App\Http\Controllers\Web\UserController;
use App\Http\Controllers\Web\WarehouseController;
use App\Http\Controllers\Web\WarehouseRackController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', ViewLoginController::class)->name('login');
Route::post('login', AttemptLoginController::class)->name('attemptLogin');
Route::get('logout', LogoutController::class)->middleware('auth')->name('logout');

Route::middleware('auth')->group(function () {
    Route::view('/', 'pages.home')->name('home');
});

Route::middleware('auth')->group(function () {
    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);

    Route::get('warehouses/export', [WarehouseController::class, 'export'])->name('warehouses.export');
    Route::post('warehouses/import', [WarehouseController::class, 'import'])->name('warehouses.import');
    Route::resource('warehouses', WarehouseController::class);

    Route::resource('warehouses.racks', WarehouseRackController::class);

    Route::get('companies/export', [CompanyController::class, 'export'])->name('companies.export');
    Route::post('companies/import', [CompanyController::class, 'import'])->name('companies.import');
    Route::resource('companies', CompanyController::class);

    Route::get('products/{product}/history', [HistoryController::class, 'showProductHistory']);
    Route::get('products/export', [ProductController::class, 'export'])->name('products.export');
    Route::post('products/import', [ProductController::class, 'import'])->name('products.import');
    Route::resource('products', ProductController::class);

    Route::resource('receives', ReceiveItemController::class);
    Route::resource('deliveries', DeliveryProductController::class);

    Route::get('formulas/{formula}/input', [FormulaController::class, 'loadFragmentInputFormula']);
    Route::resource('formulas', FormulaController::class);

    Route::get('plans/{plan}/input', [ProductionPlanController::class, 'loadFragmentInputMaterial']);
    Route::resource('plans', ProductionPlanController::class);

    Route::resource('releases', ReleaseMaterialController::class);
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];
}

app/Http/Controllers/Web/CompanyController.php
<?php

namespace App\Http\Controllers\Web;

use App\Exports\CompaniesExport;
use App\Http\Controllers\Controller;
use App\Http\Requests\CompanyRequest;
use App\Imports\CompaniesImport;
use App\Models\Company;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.companies.companies-index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.companies.companies-form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\CompanyRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
        Company::create($request->all());

        return redirect()->route('companies.index')
            ->with('toast_success', 'Created Successfully!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Company $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('pages.companies.companies-form', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\CompanyRequest  $request
     * @param  Company $company
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyRequest $request, Company $company)
    {
        $company->update($request->all());

        return redirect()->route('companies.index')
            ->with('toast_success', 'Updated Successfully!');
    }

    /**
     * Downloads an Excel file containing data from the warehouses table.
     *
     * @return void
     */
    public function export()
    {
        return Excel::download(new CompaniesExport, 'Data Company List.xlsx');
    }

    public function import(Request $request)
    {
        Excel::import(new CompaniesImport, $request->file('file'));

        return response()->json([
            'message' => 'File uploaded successfully'
        ]);
    }
}

resources/views/pages/companies/companies-form.blade.php
@extends('_layouts.base')

@section('title', 'Companies Master Management')

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-4">
            <x-form title='Company' routePrefix='companies' :param='$company ?? null'>

                <div class="row">
                    <div class="col-12">
                        {{-- Username input field --}}
                        <x-input name='name' label='Company Name' :bind='$component->model' />

                        {{-- Username input field --}}
                        <x-textarea name='address' label='Address' placeholder="(Optional)" :bind='$component->model' />

                        {{-- Username input field --}}
                        <x-select-company-tag name='companytag' label="Company As ..." :bind='$component->model' />
                    </div>
                </div>


                {{-- Save button --}}
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>

            </x-form>
        </div>
    </div>
@endsection

resources/views/pages/companies/companies-index.blade.php
@extends('_layouts.base')

@section('title', 'Companies Master Management')

@section('css')
    <!-- CSRF token for AJAX requests -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
@endsection

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-9">

            <h2> Companies Master Management </h2>

            <div class="row pl-2 mb-3">
                <!-- Create new company button -->
                <x-button-create :url="route('companies.create')" />

                <!-- Export company list button -->
                <x-button-download :url="route('companies.export')" />

                <!-- Import company list button -->
                <x-button-upload />
            </div>

            <!-- Company table -->
            <x-card body-class='p-0'>
                <x-table id='tbCompany' />
            </x-card>
        </div>
    </div>
@endsection

@section('js')
    <!-- User index page JS -->
    @vite(['resources/js/tables/table-company.js', 'resources/js/alerts/import.js'])
@endsection