routes/web.php
<?php

use App\Http\Controllers\Auth\AttemptLoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\ViewLoginController;
use App\Http\Controllers\Web\CompanyController;
use App\Http\Controllers\Web\DeliveryProductController;
use App\Http\Controllers\Web\FormulaController;
use App\Http\Controllers\Web\HistoryController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Web\ProductionPlanController;
use App\Http\Controllers\Web\ReceiveItemController;
use App\Http\Controllers\Web\ReleaseMaterialController;
use App\Http\Controllers\Web\RoleController;
use App\Http\Controllers\Web\UserController;
use App\Http\Controllers\Web\WarehouseController;
use App\Http\Controllers\Web\WarehouseRackController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', ViewLoginController::class)->name('login');
Route::post('login', AttemptLoginController::class)->name('attemptLogin');
Route::get('logout', LogoutController::class)->middleware('auth')->name('logout');

Route::middleware('auth')->group(function () {
    Route::view('/', 'pages.home')->name('home');
});

Route::middleware('auth')->group(function () {
    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);

    Route::get('warehouses/export', [WarehouseController::class, 'export'])->name('warehouses.export');
    Route::post('warehouses/import', [WarehouseController::class, 'import'])->name('warehouses.import');
    Route::resource('warehouses', WarehouseController::class);

    Route::resource('warehouses.racks', WarehouseRackController::class);

    Route::get('companies/export', [CompanyController::class, 'export'])->name('companies.export');
    Route::post('companies/import', [CompanyController::class, 'import'])->name('companies.import');
    Route::resource('companies', CompanyController::class);

    Route::get('products/{product}/history', [HistoryController::class, 'showProductHistory']);
    Route::get('products/export', [ProductController::class, 'export'])->name('products.export');
    Route::post('products/import', [ProductController::class, 'import'])->name('products.import');
    Route::resource('products', ProductController::class);

    Route::resource('receives', ReceiveItemController::class);
    Route::resource('deliveries', DeliveryProductController::class);

    Route::get('formulas/{formula}/input', [FormulaController::class, 'loadFragmentInputFormula']);
    Route::resource('formulas', FormulaController::class);

    Route::get('plans/{plan}/input', [ProductionPlanController::class, 'loadFragmentInputMaterial']);
    Route::resource('plans', ProductionPlanController::class);

    Route::resource('releases', ReleaseMaterialController::class);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, HasRoles;

    // Mass assignable attributes
    protected $guarded = ['id'];

    /**
     * Cast the password attribute to bcrypt on set
     *
     * @return \Illuminate\Database\Eloquent\Casts\Attribute
     */
    protected function password(): Attribute
    {
        return Attribute::make(
            set: fn ($value) => bcrypt($value),
        );
    }

    /**
     * Cast the role attribute to the first role of the user
     *
     * @return \Illuminate\Database\Eloquent\Casts\Attribute
     */
    protected function role(): Attribute
    {
        return Attribute::make(
            get: fn () => $this->roles->first(),
        );
    }

    // Hidden attributes
    protected $hidden = ['password'];
}

app/Http/Controllers/Web/UserController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Requests\UserRequest;
use App\Http\Controllers\Controller;
use App\Models\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.users.user-index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.users.user-form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        // Create a new user with the validated request data
        User::create($request->validated());

        // Redirect to the index page with success message
        return redirect()->route('users.index')->with('success', 'User created successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('pages.users.user-form', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\UserRequest  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user)
    {
        // Update user in the database
        $user->update($request->validated());

        // Redirect to the users index page with success message
        return redirect()->route('users.index')->with('toast_success', 'User updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        try {
            $user->delete();
            return response()->json(['message' => 'User deleted successfully'], 200);
        } catch (\Exception $e) {
            return response()->json(['message' => 'Failed to delete user'], 500);
        }
    }
}

resources/views/pages/users/user-form.blade.php
@extends('_layouts.base')

@section('title', 'Users Management')

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-6">
            <x-form title=User routePrefix=users :param=$user??null>

                <div class="row">
                    <div class="col-6">
                        {{-- Username input field --}}
                        <x-input name='username' label='Username' :bind='$component->model' />

                        {{-- Surname input field --}}
                        <x-input name='surname' label='Surname' :bind='$component->model' />

                        {{-- User role select field --}}
                        <x-select-role name='role' label='Role' :bind='$component->model' />
                    </div>
                    <div class="col-6">
                        {{-- Password input field --}}
                        <x-input type='password' name='password' label='Password' placeholder='******' />

                        {{-- Password confirmation input field --}}
                        <x-input type='password' name='password_confirmation' label='Password Confirmation' placeholder='******' />
                    </div>
                </div>

                {{-- Save button --}}
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </x-form>
        </div>
    </div>
@endsection

@section('js')
    <!-- User Form page JS -->
    @vite(['resources/js/selects/select2-initialization.js'])
@endsection

resources/views/pages/users/user-index.blade.php
@extends('_layouts.base')

@section('title', 'Users Management')

@section('css')
    <!-- CSRF token for AJAX requests -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
@endsection

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-9">

            <h2> USER MANAGEMENT </h2>

            <div class="row pl-2 mb-3">
                <!-- Create new user button -->
                <x-button-create :url="route('users.create')" />
            </div>

            <!-- User table -->
            <x-card body-class='p-0'>
                <x-table id='tbUser' />
            </x-card>
        </div>
    </div>
@endsection

@section('js')
    <!-- User index page JS -->
    @vite(['resources/js/tables/table-user.js'])
@endsection