routes/web.php
<?php

use App\Http\Controllers\Auth\AttemptLoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\ViewLoginController;
use App\Http\Controllers\Web\CompanyController;
use App\Http\Controllers\Web\DeliveryProductController;
use App\Http\Controllers\Web\FormulaController;
use App\Http\Controllers\Web\HistoryController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Web\ProductionPlanController;
use App\Http\Controllers\Web\ReceiveItemController;
use App\Http\Controllers\Web\ReleaseMaterialController;
use App\Http\Controllers\Web\RoleController;
use App\Http\Controllers\Web\UserController;
use App\Http\Controllers\Web\WarehouseController;
use App\Http\Controllers\Web\WarehouseRackController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', ViewLoginController::class)->name('login');
Route::post('login', AttemptLoginController::class)->name('attemptLogin');
Route::get('logout', LogoutController::class)->middleware('auth')->name('logout');

Route::middleware('auth')->group(function () {
    Route::view('/', 'pages.home')->name('home');
});

Route::middleware('auth')->group(function () {
    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);

    Route::get('warehouses/export', [WarehouseController::class, 'export'])->name('warehouses.export');
    Route::post('warehouses/import', [WarehouseController::class, 'import'])->name('warehouses.import');
    Route::resource('warehouses', WarehouseController::class);

    Route::resource('warehouses.racks', WarehouseRackController::class);

    Route::get('companies/export', [CompanyController::class, 'export'])->name('companies.export');
    Route::post('companies/import', [CompanyController::class, 'import'])->name('companies.import');
    Route::resource('companies', CompanyController::class);

    Route::get('products/{product}/history', [HistoryController::class, 'showProductHistory']);
    Route::get('products/export', [ProductController::class, 'export'])->name('products.export');
    Route::post('products/import', [ProductController::class, 'import'])->name('products.import');
    Route::resource('products', ProductController::class);

    Route::resource('receives', ReceiveItemController::class);
    Route::resource('deliveries', DeliveryProductController::class);

    Route::get('formulas/{formula}/input', [FormulaController::class, 'loadFragmentInputFormula']);
    Route::resource('formulas', FormulaController::class);

    Route::get('plans/{plan}/input', [ProductionPlanController::class, 'loadFragmentInputMaterial']);
    Route::resource('plans', ProductionPlanController::class);

    Route::resource('releases', ReleaseMaterialController::class);
});

app/Http/Controllers/Web/RoleController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Http\Requests\RoleRequest;
use Illuminate\Support\Facades\Cache;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.roles.role-index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::get();
        return view('pages.roles.role-form', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\RoleRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RoleRequest $request)
    {
        // Create a new user with the validated request data
        $role = Role::create($request->validated());
        $role->syncPermissions($request->permissions);

        Cache::forget('roles');

        // Redirect to the index page with success message
        return redirect()->route('roles.index')->with('success', 'Role created successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $permissions = Permission::get();
        return view('pages.roles.role-form', compact('role', 'permissions'));
    }
}

resources/views/pages/roles/role-form.blade.php
@extends('_layouts.base')

@section('title', 'Roles Management')

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-6">
            <x-form title=Role routePrefix=roles :param=$role??null>

                <div class="row">
                    <div class="col-12">
                        {{-- Role Name input field --}}
                        <x-input name='name' label='1. Role Name' :bind='$component->model' />
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                         {{-- Permissions input field --}}
                         <x-checkbox-permission name='permissions[]' label='2. Give Access To' :options=$permissions :bind='$component->model' />
                    </div>
                </div>

                {{-- Save button --}}
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </x-form>
        </div>
    </div>
@endsection

resources/views/pages/roles/role-index.blade.php
@extends('_layouts.base')

@section('title', 'Roles Management')

@section('css')
    <!-- CSRF token for AJAX requests -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
@endsection

@section('content')
    <div class="row d-flex justify-content-center">
        <div class="col-9">

            <h2> ROLE MANAGEMENT </h2>

            <div class="row pl-2 mb-3">
                <!-- Create new role button -->
                <x-button-create :url="route('roles.create')" />
            </div>

            <!-- Role table -->
            <x-card body-class='p-0'>
                <x-table id='tbRole' />
            </x-card>
        </div>
    </div>
@endsection

@section('js')
    <!-- Role index page JS -->
    @vite(['resources/js/tables/table-role.js'])
@endsection